### PR TITLE
feat(rust): use standalone installer

### LINKED ISSUE #42: Rust temporary file problem
When using binarySource=docker:

```
Command failed: docker run --rm --name=renovate_rust --label=renovate_child -v "/tmp/renovate/repos/github/renovate-tests/tikv":"/tmp/renovate/repos/github/renovate-tests/tikv" -v "/tmp/renovate/cache":"/tmp/renovate/cache" -w "/tmp/renovate/repos/github/renovate-tests/tikv" renovate/rust bash -l -c "cargo update --manifest-path Cargo.toml --package fail"
info: syncing channel updates for 'nightly-2020-04-23-x86_64-unknown-linux-gnu'
error: could not create temp file: /usr/local/rust/tmp/wq376y4cw_nr6daw_file
error: backtrace:
error: stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: rustup::dist::download::DownloadCfg::download_and_check
   2: rustup::dist::dist::dl_v2_manifest
   3: rustup::dist::dist::try_update_from_dist_
   4: rustup::toolchain::Toolchain::install
   5: rustup::toolchain::Toolchain::install_from_dist
   6: rustup::config::Cfg::find_override
   7: rustup::config::Cfg::find_override_toolchain_or_default
   8: rustup::config::Cfg::toolchain_for_dir
   9: rustup_init::run_rustup_inner
  10: rustup_init::main
  11: std::rt::lang_start::{{closure}}
  12: main
  13: __libc_start_main
  14: <unknown>
```

Seems it wants to write to `/usr/local/rust`

Maybe can be resolved with an env setting, but I'm still not sure why we can't grant `ubuntu` user access to `/usr/local/`?

### PR DESCRIPTION
**Pull request by viceice**
closes #42, #43

### CODE REVIEW

**Comment by viceice** [comment]
@rarkins What do you think about this solution? We can Use `CARGO_HOME` to overwrite the cache to  `<renovate>/cache/cargo` for renovate app /cli

**Comment by rarkins** [comment]
It's definitely more complex. The benefit is that CARGO_HOME is configurable?

**Comment by viceice** [comment]
yes, it falls back to `$HOME/.cargo` by default

**Comment by rarkins** [comment]
ok, let's try it. why also the check for duplicate install? is there a scenario where that's likely?

**Comment by viceice** [comment]
no, just copy'n'paste from ruby/python, where i do the same. so i someone tries to install twice it will do nothing instead of fail with folder exists / overwrite fail

**Comment by rarkins** [comment]
OK, approve if you're happy with it

**Comment by viceice** [comment]
We do save 13MB of disk space 🙃

**Pull request merged**
