### PR TITLE
feat: add global wrapper

### PR DESCRIPTION
**Pull request by viceice**
- [x] add shell wrapper for `install-tool`
- [ ] add shell wrapper for `install-pip`
- [ ] add shell wrapper for `install-gem`

not needed (needs refactoring):
- java
- erlang
- docker
- php
- composer

ref #163

### CODE REVIEW

**Comment by viceice** [comment]
for pip and gem it would only work if the tool name and the final executable have same name.

**Comment by viceice** [comment]
The wrapper only works for root install, because otherwise we don't have the right to create it. 😕

**Comment by rarkins** [comment]
Let's de prioritize this for now although maybe making our tool after the final binary is good if we can do it

**Comment by viceice** [comment]
So i would like to have this merged as is, because i need for other projects too, eg jenkins docker slaves 😉 

This will also help most users debugging issues in renovate full and on premise image.

**Comment by rarkins** [comment]
Merge when you want

**Pull request merged**
